#!/bin/sh
set -e

INSTALL_VERSION=3.4.0

if [ "$1" != "" ]; then
    INSTALL_VERSION=$1
fi

sudo curl -LO https://github.com/phalcon/phalcon-devtools/archive/v${INSTALL_VERSION}.tar.gz
sudo tar xzf v${INSTALL_VERSION}.tar.gz
sudo rm -rf v${INSTALL_VERSION}.tar.gz
sudo mv phalcon-devtools-${INSTALL_VERSION} /usr/src/phalcon-devtools
sudo ln -sf /usr/src/phalcon-devtools/phalcon.php /usr/local/bin/phalcon
